---
- name: check nginx installed
  apt: name=nginx state=present update_cache=yes
- name: start nginx
  service:
    name: nginx
    state: started
- name: copy nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
  - restart nginx
- file: path=/var/www/ owner=nobody group=nogroup mode=0755 state=directory
- file: path=/var/log/nginx owner=nobody group=nogroup mode=0755 state=directory